### ISSUE TITLE
With Hive 1.1.0 not working

### ISSUE THREAD

**Issue by nicolamarangoni** [exasol/virtual-schemas#388] opened 2020-09-14 13:17 UTC
Hi,

we would like to create virtual schemas on Hive 1.1.0 but it's not working.

We get the error message:
```
SQL Error [22002]: VM error: 
com.exasol.adapter.AdapterException: Unable create Virtual Schema "HIVE_TEST". Cause: "No suitable driver found for jdbc:hive2://app-qhaphiv-vc1.fhm.de:10000
Stack trace:
com.exasol.adapter.jdbc.JdbcAdapter.createVirtualSchema(JdbcAdapter.java:39)
com.exasol.adapter.RequestDispatcher.dispatchCreateVirtualSchemaRequestToAdapter(RequestDispatcher.java:110)
com.exasol.adapter.RequestDispatcher.processRequest(RequestDispatcher.java:70)
com.exasol.adapter.RequestDispatcher.executeAdapterCall(RequestDispatcher.java:52)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:41)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:95) (Session: 1677814156554256568)
```
We have Hive 1.1.0 and use the `jdbc-driver hive-jdbc-1.1.0-cdh5.16.2-standalone.jar`.

Best regards
Nicola

**Comment by nicolamarangoni** [comment] 2020-09-14 13:23
I've updated to the newest release of the virtual schema adapter and now I get the following:
```
SQL Error [22002]: VM error: 
com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create Hive remote metadata reader.
Stack trace:
com.exasol.adapter.dialects.hive.HiveSqlDialect.createRemoteMetadataReader(HiveSqlDialect.java:126)
com.exasol.adapter.dialects.AbstractSqlDialect.readSchemaMetadata(AbstractSqlDialect.java:138)
com.exasol.adapter.jdbc.JdbcAdapter.readMetadata(JdbcAdapter.java:56)
com.exasol.adapter.jdbc.JdbcAdapter.createVirtualSchema(JdbcAdapter.java:33)
com.exasol.adapter.RequestDispatcher.dispatchCreateVirtualSchemaRequestToAdapter(RequestDispatcher.java:110)
com.exasol.adapter.RequestDispatcher.processRequest(RequestDispatcher.java:70)
com.exasol.adapter.RequestDispatcher.executeAdapterCall(RequestDispatcher.java:52)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:41)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:95) (Session: 1677814156554256568)
```

**Comment by nicolamarangoni** [comment] 2020-09-14 13:30
Another update: using the hive driver `hive-jdbc-2.3.7-standalone.jar` I get the same error

**Comment by nicolamarangoni** [comment] 2020-09-14 13:33
On the other end, if I use` hive-jdbc-2.3.7-standalone.jar` with version 3.1.0 of the adapte I get the following error:
```
SQL Error [22002]: VM error: 
com.exasol.adapter.AdapterException: Unable create Virtual Schema "HIVE_TEST". Cause: "Could not open client transport with JDBC Uri: jdbc:hive2://app-qhaphiv-vc1.fhm.de:10000: Could not establish connection to jdbc:hive2://app-qhaphiv-vc1.fhm.de:10000: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{set:hiveconf:hive.server2.thrift.resultset.default.fetch.size=1000, use:database=default})
Stack trace:
com.exasol.adapter.jdbc.JdbcAdapter.createVirtualSchema(JdbcAdapter.java:39)
com.exasol.adapter.RequestDispatcher.dispatchCreateVirtualSchemaRequestToAdapter(RequestDispatcher.java:110)
com.exasol.adapter.RequestDispatcher.processRequest(RequestDispatcher.java:70)
com.exasol.adapter.RequestDispatcher.executeAdapterCall(RequestDispatcher.java:52)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:41)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:95) (Session: 1677814156554256568)
```

**Comment by AnastasiiaSergienko** [comment] 2020-09-14 13:48
Hello @nicolamarangoni !

For the first error message: as the driver you are using is different from the recommended one, you need to find and register the right parameters for it in EXAOperation (main class, prefix, files). You could also check carefully the driver name in the adapter script, maybe you copied and pasted it with typos. 

Unfortunately, we have not tested the hive dialect with Hive 1.1.0. The latest tested Hive version is 2.3.2. 
Also, the drivers you're using are not tested too, we recommend using Hive JDBC Connector if it's possible (check the link here: https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/hive.md).

The second exception doesn't contain any valuable information. We need logs from virtual schemas to diagnose a problem. Please, check how to start remote logging here: https://docs.exasol.com/database_concepts/virtual_schema/logging.htm

The third error sounds like a connection problem. You could try to connect to Hive with that driver without Virtual Schemas first to test the connection.

If your problem persists we will need logs and the statements you used to create an adapter script, virtual schema, and connection (please, be careful with your private information).

Best Regards,
Anastasiia Sergienko

**Comment by nicolamarangoni** [comment] 2020-09-14 15:17
Hello @AnastasiiaSergienko,
I cannot use the hive driver of version > 2.x with dbeaver. I get the same error:
`'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{set:hiveconf:hive.server2.thrift.resultset.default.fetch.size=1000, use:database=default})`
I suppose that I should use the 1.1.0 deiver in any case.
I have already correctly registered the driver 1.1.0 in ExaOperations and it works, I can import from tables in Hive.

This is the adapter DDL:
```
CREATE OR REPLACE JAVA ADAPTER SCRIPT adapter.jdbc_adapter_hive AS
  %scriptclass com.exasol.adapter.RequestDispatcher;
  %jar /buckets/bucketfs1/bucket_adapter/virtualschema-jdbc-adapter-dist-3.1.0.jar;
  %jar /buckets/bucketfs1/bucket_adapter/hive-jdbc-1.1.0.jar;
/
```

The driver-file has the name `hive-jdbc-1.1.0.jar` in both EXAOperations and in the bucket.
The class name is org.apache.hive.jdbc.HiveDriver and is correctly configured in EXAOperations (imports work).

Best regards,
Nicola

**Comment by nicolamarangoni** [comment] 2020-09-14 16:33
Hello @AnastasiiaSergienko ,
I also discovered the following:
`virtualschema-jdbc-adapter-dist-3.1.0.jar` show more details in the error message, while `virtual-schema-dist-5.0.4-bundle-4.0.3.jar` just give back the generic message in my 2nd question: `com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create Hive remote metadata reader`, I discovered it with another adapter/connection to MS SQLSever.

Using 3.1.0:
`com.exasol.adapter.AdapterException: Unable create Virtual Schema "myVirtualShema". Cause: "The TCP/IP connection to the host 123.123.123.123, port 1433 has failed. Error: "Connection refused (Connection refused). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".`

Using 4.0.3:
`com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create Hive remote metadata reader`

So it is quite possible that the problem with the JDBC driver for Hive is always the same but version 4.0.3 just give back a generic error message.

The behaviour of version 3.1.0 of the adapter look much better when errors occur.

Best regards,
Nicola

**Comment by AnastasiiaSergienko** [comment] 2020-09-15 05:48
Hi @nicolamarangoni ,

I'm glad to hear that you were able to connect to Hive via Virtual Schemas! 

Thank you for reporting your experiments. I'll create a ticket and investigate the error handling in our latest version. It definitely looks better in 3.1.0 with all those details.

Please let us know if you have more questions.

Best Regards,
Anastasiia Sergienko

**Comment by AnastasiiaSergienko** [comment] 2020-09-18 12:42
I'm closing this issue for now. Please, feel free to re-open it if some other questions appear.

**Closed by AnastasiiaSergienko** 2020-09-18 12:42 UTC
Labels: question

**Comment by nicolamarangoni** [comment] 2020-09-23 10:09
Hi @AnastasiiaSergienko,

just to precise:
what I can do is to create a CONNECTION and then perform an IMPORT on tables in hive using the driver 1.1.x.
What I cannot do is to create a virtual schema. I still get "No suitable driver found".
I have the impression that the adapter simply doesn't work for Hive < 2.x.x.
So if you plan to test and eventually fix the adapter with Hive 1.1.x you can reopen the issue, otherwise you can leave it closed.

Best regards,
Nicola

**Comment by AnastasiiaSergienko** [comment] 2020-09-28 09:08
Hello @nicolamarangoni ,

we have investigated the problem you reported. So, the driver you use has two problems so far, one of them can be solved and the other one actually can't, so we strongly recommend upgrading a Hive and use another driver if you want to use Hive with the Virtual Schemas.

The test was performed with:
* Hive version: 1.1.0
* Hive JDBC driver: jdbc-driver hive-jdbc-1.1.0-cdh5.16.2-standalone.jar

The problems are:

1) The driver does not register itself automatically, and it caused the problem you've reported. It's actually a bug in the driver. To fix it, you need to add a file `META-INF/services/java.sql.Driver` inside the jar archive. In this file, you need to register the main driver's class. In our case it is  `org.apache.hive.jdbc.HiveDriver`. This fixes the problem of the `No suitable driver found` exception.

 But here we encounter the second issue:

2)  The exception is
`com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create schema adapter notes from remote schema.
	at  
        ....
Caused by: java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveDatabaseMetaData.storesLowerCaseIdentifiers(HiveDatabaseMetaData.java:820)
	at com.exasol.adapter.jdbc.AbstractRemoteMetadataReader.getSchemaAdapterNotes(AbstractRemoteMetadataReader.java:159)
	... 13 more
`
This means that the driver doesn't support a method that the Virtual Schema uses to collect the metadata, so it's not possible to create a Hive dialect with this JDBC driver. We don't want to change this behavior, because the newer Hive drivers work fine here and it's not nice to hardcode the metadata only because of an old driver that contains bugs.

Please, always feel free to contact us if you have more questions.

Best Regards,
Anastasiia Sergienko

**Comment by nicolamarangoni** [comment] 2020-09-29 07:39
Dear @AnastasiiaSergienko ,

many thanks for your analysis.
The Hive-driver 2.x doesn't work with version 1.1.x on our server. Therefore we will try to create these virtual schemas after the upgrade to Hive 2.x or 3.x next year.

Best regards,

Nicola Marangoni
